### ISSUE TITLE
[Eventos] PHP TestFest Brasil 2017! 

### ISSUE THREAD

**Issue by devbrunocorrea** [php-pr/forum#6]
Confesso que ainda não estou tão inteirado sobre o assunto, mas gostaria de deixar aqui a sugestão para que o grupo PHPPR participe também desta ação que visa melhorar a qualidade do PHP.

**PHP TestFest Brasil 2017!** 
https://phptestfestbrasil.github.io/

**Comment by nandomoreirame** [comment]
Pow legal @devbrunocorrea , obrigado por compartilhar!
Inclusive esse foi um assunto discutido no meetup no dia 11/07, iremos montar um grupo para participar sim, espero que vc participe conosco 👍

**Comment by rogeriopradoj** [comment]
Olá! Fica o convite para entrarem lá no https://t.me/PHPTestFestBrasil , onde várias comunidades BR estão juntas! Vários grupos também já seguiram os passos aí do Paraná e estão conseguindo fazer seus eventos presenciais.

E quem topa participar de um #phptestfest online, junto as com várias comunidades BR no #PHPTestFestBrasil? Estamos pegando uma melhor data para mais pessoas no https://doodle.com/poll/cxkfxk64imsgaz4v. Até lá!

~~~
Rogério
@RogerioPradoJ
(antes em São Paulo, PHPSP, agora em Brasília, PHPDF)!
